language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        aH92YU+DITYt1nLkSMv+P50vuv3LFa81aLRveTAjArMfytOnmrjTx6+luB4J1HE8EMMnx7QgCvOGKicSv0nuF49HEagaymJIbguXlSnOE4AxBDoEKzT3R1F+GJbroJr3cAbFUZ/EVI8YBLDYMjyPM+1LRsZk0hf4BaKqxpRNIwk=
    - secure: >-
        cA6JFPS+oerdFAWUri3/FpdcfjJsA2BfwZIiKojueJVDjnUS2bsTVe1XzmBmYnHipikO/wXiDmL8ST9VG7xDN5McwR+lD2kxMfH8ERW/j52yZbHs3famjjZ84TFmY1IhK32kV6cDuR9X2yJT9SnYWdJXAMTN79m+B/En2PdTJ7I=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
